# Generated by Django 5.2.11 on 2026-10-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0023_alter_permission_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    'is_active',
                    models.BooleanField(
                        default=True, help_text='Whether the app is currently installed on this store.'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        help_text='The tenant that owns this Shopify store connection. Null if redacted.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='shopify_stores',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopifyToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    '_encrypted_access_token',
                    models.CharField(blank=True, db_column='access_token_encrypted', max_length=512, null=True),
                ),
                (
                    'scopes',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Comma-separated scopes granted by the merchant.',
                        max_length=1024,
                    ),
                ),
                (
                    'store',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='token', to='shopify.shopifystore'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
