# Generated by Django 5.2.11 on 2026-09-30 19:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0023_alter_permission_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayFastCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m_payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'kind',
                    models.CharField(
                        choices=[('subscription', 'Subscription'), ('donation', 'Donation')], max_length=16
                    ),
                ),
                ('plan', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    'frequency',
                    models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Monthly'), (6, 'Annual')], null=True),
                ),
                ('is_trial', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=16
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payfast_checkouts',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'PayFast checkout',
            },
        ),
        migrations.CreateModel(
            name='PayFastSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(default='free_plan', max_length=32)),
                ('pending_plan', models.CharField(blank=True, default='', max_length=32)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('trialing', 'Trialing'),
                            ('past_due', 'Past due'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='active',
                        max_length=16,
                    ),
                ),
                ('token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                (
                    'frequency',
                    models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Monthly'), (6, 'Annual')], null=True),
                ),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('has_used_trial', models.BooleanField(default=False)),
                ('trial_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('payment_failed_notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                (
                    'tenant',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payfast_subscription',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'PayFast subscription',
            },
        ),
        migrations.CreateModel(
            name='PayFastPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'kind',
                    models.CharField(
                        choices=[('subscription', 'Subscription'), ('donation', 'Donation')], max_length=16
                    ),
                ),
                ('plan', models.CharField(blank=True, default='', max_length=32)),
                ('pf_payment_id', models.CharField(max_length=64, unique=True)),
                ('m_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(max_length=16)),
                ('item_name', models.CharField(blank=True, default='', max_length=100)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('raw', models.JSONField(blank=True, default=dict)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payfast_payments',
                        to='multitenancy.tenant',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='payments',
                        to='payfast.payfastsubscription',
                    ),
                ),
            ],
            options={
                'verbose_name': 'PayFast payment',
                'ordering': ('-created_at',),
            },
        ),
    ]
