# Generated by Django 5.2.11 on 2026-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payfast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfastcheckout',
            name='replaces_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payfastsubscription',
            name='superseded_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
