# Generated by Django 5.2.11 on 2026-10-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payfast', '0002_plan_change_by_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfastpayment',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
    ]
