# Generated by Django 5.2.11 on 2026-08-01 20:19

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_useravatar_original_alter_useravatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='original',
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicCloudflareR2Storage(),
                upload_to=common.storages.UniqueFilePathGenerator('avatars'),
            ),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='thumbnail',
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicCloudflareR2Storage(),
                upload_to=common.storages.UniqueFilePathGenerator('avatars/thumbnails'),
            ),
        ),
    ]
